update employee_clinical_role_mappings set clinical_role_id=20 where clinical_role_id=12;
delete from clinical_roles where id=12;
update clinical_roles set description='clinical radiologist (including residents, attendings, etc.)' where id=1;
update clinical_roles set description='resident' where id=2;
update clinical_roles set description='attending physician of any discipline (radiologist, ED doctor, pediatrician, etc)' where id=3;
update clinical_roles set description='fellow in an ACGME-accredited program' where id=4;
update clinical_roles set description='fellow in a non-ACGME-accredited program' where id=5;
update clinical_roles set description='technologists (modality techs, lab techs, etc)' where id=6;
update clinical_roles set description='non-physician administrative role for those who transcribe and edit reports, handle corrections, etc.' where id=7;
update clinical_roles set description='clinical administrative role for employees who check in patients, verify patient information, etc.' where id=8;
update clinical_roles set description='non-clinical role for employees working in billing, accounting, etc.' where id=9;
update clinical_roles set description='general administrative, non-clinical role' where id=10;
update clinical_roles set description='technical administrators who support clinical systems (PACS admins, RIS admins, etc.)' where id=11;
update clinical_roles set description='Those in a supervisory role in their position (tech supervisors, RIS/PACS manager, section chiefs)' where id=13;
update clinical_roles set description='Those in director positions for their given role (director titles)' where id=14;
update clinical_roles set description='Those in executive positions (Hospital C level, Department chair, department administrator)' where id=15;
update clinical_roles set description='Senior or lead team members who are not supervisors, but have extra system privileges or leadership roles' where id=16;
update clinical_roles set description='coders and others who work on billing, insurance, claims, etc.' where id=17;
update clinical_roles set description='nursing staff' where id=18;
update clinical_roles set description='staff who transport patients' where id=19;
update clinical_roles set description='senior technical administrators or vendor support staff (synonym of deprecated support-staff)' where id=20;
update clinical_roles set description='researchers and other informaticians' where id=21;
