#!/usr/bin/ruby

threshold_in_seconds = 3600
ftpdir = "/servers/ftp/incoming"

if not File.directory?(ftpdir)
  print "FTP directory #{ftpdir} does not exist"
  exit 1
end

if ( (Time.now - threshold_in_seconds) < File.mtime(ftpdir) )
  print "New files exist in #{ftpdir}"
  exit 2
end

print "No new files"
exit
