--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

--
-- Name: cms_facility_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: harbinger
--

SELECT pg_catalog.setval('cms_facility_types_id_seq', 43, true);


--
-- Data for Name: cms_facility_types; Type: TABLE DATA; Schema: public; Owner: harbinger
--

INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (1, 1, 'Pharmacy - A facility or location where drugs and other medically related items and services are sold, dispensed, or otherwise provided directly to patients', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (2, 3, 'School - A facility whose primary purpose is education.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (3, 4, 'Homeless Shelter - A facility or location whose primary purpose is to provide temporary housing to homeless individuals (e.g., emergency shelters, individual or family shelters).', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (4, 5, 'Indian Health Service Free-standing Facility - A facility or location, owned and operated by the Indian Health Service, which provides diagnostic, therapeutic (surgical and non-surgical), and rehabilitation services to American Indians and Alaska Natives who do not require hospitalization.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (5, 6, 'Indian Health Service Provider-based Facility - A facility or location, owned and operated by the Indian Health Service, which provides diagnostic, therapeutic (surgical and non-surgical), and rehabilitation services rendered by, or under the supervision of, physicians to American Indians and Alaska Natives admitted as inpatients or outpatients.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (6, 7, 'Tribal 638 Free-Standing Facility - A facility or location owned and operated by a federally recognized American Indian or Alaska Native tribe or tribal organization under a 638 agreement, which provides diagnostic, therapeutic (surgical and nonsurgical), and rehabilitation services to tribal members who do not require hospitalization.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (7, 8, 'Tribal 638 Provider-Based Facility - A facility or location owned and operated by a federally recognized American Indian or Alaska Native tribe or tribal organization under a 638 agreement, which provides diagnostic, therapeutic (surgical and nonsurgical), and rehabilitation services to tribal members admitted as inpatients or outpatients.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (8, 9, 'Prison/Correctional Facility - A prison, jail, reformatory, work farm, detention center, or any other similar facility maintained by either Federal, State or local authorities for the purpose of confinement or rehabilitation of adult or juvenile criminal offenders.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (9, 11, 'Office - Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (10, 12, 'Home - Location, other than a hospital or other facility, where the patient receives care in a private residence.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (11, 13, 'Assisted Living Facility - Congregate residential facility with self-contained living units providing assessment of each resident''s needs and on-site support 24 hours a day, 7 days a week, with the capacity to deliver or arrange for services including some health care and other services.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (12, 14, 'Group Home - A residence, with shared living areas, where clients receive supervision and other services such as social and/or behavioral services, custodial service, and minimal services (e.g., medication administration).', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (13, 15, 'Mobile Unit - A facility/unit that moves from place-to-place equipped to provide preventive, screening, diagnostic, and/or treatment services.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (14, 20, 'Urgent Care Facility - Location, distinct from a hospital emergency room, an office, or a clinic, whose purpose is to diagnose and treat illness or injury for unscheduled, ambulatory patients seeking immediate medical attention.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (15, 21, 'Inpatient Hospital - A facility, other than psychiatric, which primarily provides diagnostic, therapeutic (both surgical and nonsurgical), and rehabilitation services by, or under, the supervision of physicians to patients admitted for a variety of medical conditions.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (16, 22, 'Outpatient Hospital - A portion of a hospital which provides diagnostic, therapeutic (both surgical and nonsurgical), and rehabilitation services to sick or injured persons who do not require hospitalization or institutionalization.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (17, 23, 'Emergency Room-Hospital - A portion of a hospital where emergency diagnosis and treatment of illness or injury is provided.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (18, 24, 'Ambulatory Surgical Center - A freestanding facility, other than a physician''s office, where surgical and diagnostic services are provided on an ambulatory basis.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (19, 25, 'Birthing Center - A facility, other than a hospital''s maternity facilities or a physician''s office, which provides a setting for labor, delivery, and immediate postpartum care as well as immediate care of newborn infants.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (20, 26, 'Military Treatment Facility - A medical facility operated by one or more of the Uniformed Services. Military Treatment Facility (MTF) also refers to certain former U.S. Public Health Service (USPHS) facilities now designated as Uniformed Service Treatment Facilities (USTF).', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (21, 31, 'Skilled Nursing Facility - A facility which primarily provides inpatient skilled nursing care and related services to patients who require medical, nursing, or rehabilitative services but does not provide the level of care or treatment available in a hospital.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (22, 32, 'Nursing Facility - A facility which primarily provides to residents skilled nursing care and related services for the rehabilitation of injured, disabled, or sick persons, or, on a regular basis, health-related care services above the level of custodial care to other than mentally retarded individuals.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (23, 33, 'Custodial Care Facility - A facility which provides room, board and other personal assistance services, generally on a longterm basis, and which does not include a medical component.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (24, 34, 'Hospice - A facility, other than a patient''s home, in which palliative and supportive care for terminally ill patients and their families are provided.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (25, 41, 'Ambulance (Land) - A land vehicle specifically designed, equipped and staffed for lifesaving and transporting the sick or injured.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (26, 42, 'Ambulance (Air or Water) - An air or water vehicle specifically designed, equipped and staffed for lifesaving and transporting the sick or injured.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (27, 49, 'Independent Clinic - A location, not part of a hospital and not described by any other Place of Service code, that is organized and operated to provide preventive, diagnostic, therapeutic, rehabilitative, or palliative services to outpatients only.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (28, 50, 'Federally Qualified Health Center - A facility located in a medically underserved area that provides Medicare beneficiaries preventive primary medical care under the general direction of a physician.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (29, 51, 'Inpatient Psychiatric Facility - A facility that provides inpatient psychiatric services for the diagnosis and treatment of mental illness on a 24-hour basis, by or under the supervision of a physician.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (30, 52, 'Psychiatric Facility-Partial Hospitalization - A facility for the diagnosis and treatment of mental illness that provides a planned therapeutic program for patients who do not require full time hospitalization, but who need broader programs than are possible from outpatient visits to a hospital-based or hospital-affiliated facility.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (31, 53, 'Community Mental Health Center - A facility that provides the following services: outpatient services, including specialized outpatient services for children, the elderly, individuals who are chronically ill, and residents of the CMHC''s mental health services area who have been discharged from inpatient treatment at a mental health facility; 24 hour a day emergency care services; day treatment, other partial hospitalization services, or psychosocial rehabilitation services; screening for patients being considered for admission to State mental health facilities to determine the appropriateness of such admission; and consultation and education services.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (32, 54, 'Intermediate Care Facility/Mentally Retarded - A facility which primarily provides health-related care and services above the level of custodial care to mentally retarded individuals but does not provide the level of care or treatment available in a hospital or SNF.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (33, 55, 'Residential Substance Abuse Treatment Facility - A facility which provides treatment for substance (alcohol and drug) abuse to live-in residents who do not require acute medical care. Services include individual and group therapy and counseling, family counseling, laboratory tests, drugs and supplies, psychological testing, and room and board.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (34, 56, 'Psychiatric Residential Treatment Center - A facility or distinct part of a facility for psychiatric care which provides a total 24-hour therapeutically planned and professionally staffed group living and learning environment.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (35, 57, 'Non-residential Substance Abuse Treatment Facility - A location which provides treatment for substance (alcohol and drug) abuse on an ambulatory basis. Services include individual and group therapy and counseling', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (36, 60, 'Mass Immunization Center - A location where providers administer pneumococcal pneumonia and influenza virus vaccinations and submit these services as electronic media claims, paper claims, or using the roster billing method. This generally takes place in a mass immunization setting, such as, a public health center, pharmacy, or mall but may include a physician office setting.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (37, 61, 'Comprehensive Inpatient Rehabilitation Facility - A facility that provides comprehensive rehabilitation services under the supervision of a physician to inpatients with physical disabilities. Services include physical therapy, occupational therapy, speech pathology, social or psychological services, and orthotics and prosthetics services.', true, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (38, 62, 'Comprehensive Outpatient Rehabilitation Facility - A facility that provides comprehensive rehabilitation services under the supervision of a physician to outpatients with physical disabilities. Services include physical therapy, occupational therapy, and speech pathology services.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (39, 65, 'End-Stage Renal Disease Treatment Facility - A facility other than a hospital, which provides dialysis treatment, maintenance, and/or training to patients or caregivers on an ambulatory or home-care basis.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (40, 71, 'State or Local Public Health Clinic - A facility maintained by either State or local health departments that provides ambulatory primary medical care under the general direction of a physician.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (41, 72, 'Rural Health Clinic - A certified facility which is located in a rural medically underserved area that provides ambulatory primary medical care under the general direction of a physician.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (42, 81, 'Independent Laboratory - A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician''s office.', false, now());
INSERT INTO cms_facility_types (id, pos_code, facility_type, cms_facility, updated_at) VALUES (43, 99, 'Other Place of Service - Other place of service not identified above', false, now());


--
-- PostgreSQL database dump complete
--

