-- old: 2.3.23 542ccdad95d27ce75b128bcb68deba36e7fdd2b0
-- new: 2.3.24 19a1a0c81ab4adea7e8bc3981e23f28872776358

INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (12, 'billed', 'the procedure has been sent to the billing company, but not necessarily coded or charged or collected', now());                                                                                     
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (13, 'charged', 'the claim has been charged to a carrier or individual, but not necessarily collected entirely', now());                                                                                            
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (14, 'denied', 'the claim has been denied', now());                                                                                                                                                                 
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (15, 'appealed', 'the claim denial has been appealed', now());                                                                                                                                                      
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (16, 'collected', 'the claim has been collected, but not necessarily entirely', now());                                                                                                                             
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (17, 'fully collected', 'the claim has been fully collected', now());                                                                                                                                               
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (18, 'admit', 'patient admitted to hospital', now());                                                                                                                                                               
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (19, 'transfer', 'patient has been moved/transferred to another location', now());                                                                                                                                  
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (20, 'discharge', 'patient has been discharged', now());                                                                                                                                                            
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (21, 'register', 'patient has been registered', now());                                                                                                                                                             
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (22, 'pre-admit', 'patient is not yet admitted', now());                                                                                                                                                            
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (23, 'cancel admit', 'patient admission has been cancelled', now());                                                                                                                                                
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (24, 'cancel discharge', 'patient discharge has been cancelled', now());                                                                                                                                            
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (25, 'cancel', 'exam has been cancelled', now());                                                                                                                                                                   
INSERT INTO trip_statuses (id, status, description, updated_at) VALUES (26, 'corrections', 'report is being revised for corrections', now());
UPDATE public.configuration_variables SET configuration_value='19a1a0c81ab4adea7e8bc3981e23f28872776358', updated_at=now() WHERE configuration_key='data-model-commit-id';