#!/bin/sh
#
# CDDL HEADER START
# 
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
# 
# You can obtain a copy of the license at
# https://OpenDS.dev.java.net/OpenDS.LICENSE.
# See the License for the specific language governing permissions
# and limitations under the License.
# 
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at
# trunk/opends/resource/legal-notices/OpenDS.LICENSE.  If applicable,
# add the following below this CDDL HEADER, with the fields enclosed
# by brackets "[]" replaced with your own identifying information:
#      Portions Copyright [yyyy] [name of copyright owner]
# 
# CDDL HEADER END
# chkconfig: 345 95 5
# description: Control the OpenDJ Directory Server


# Set the path to the OpenDJ instance to manage
INSTALL_ROOT="/servers/opendj/OpenDJ-2.4.3"
export INSTALL_ROOT

cd ${INSTALL_ROOT}

# Determine what action should be performed on the server
case "${1}" in
start)
  /bin/su opendj -c "${INSTALL_ROOT}/bin/start-ds --quiet"
  exit ${?}
  ;;
stop)
  /bin/su opendj -c "${INSTALL_ROOT}/bin/stop-ds --quiet"
  exit ${?}
  ;;
status)
  /bin/su opendj -c "${INSTALL_ROOT}/bin/status -n"
  exit ${?}
  ;;
restart)
  /bin/su opendj -c "${INSTALL_ROOT}/bin/stop-ds --restart --quiet"
  exit ${?}
  ;;
*)
  echo "Usage:  $0 { start | stop | restart }"
  exit 1
  ;;
esac
